### ISSUE TITLE
No module named 'math'

### ISSUE THREAD

**Issue by SkinnyPigeon** [cube-js/cube_dbt#1]
Hey folks, whenever I try to import `cube_dbt` into my `model/globals.py` module I get the error `Error: Python error: ModuleNotFoundError: No module named 'math'`. However, if I start a Python interpreter the import works correctly and I am able to import the manifest as expected.

I am running Cube version 0.34.3 on an M1 Mac

**Comment by SkinnyPigeon** [comment]
As some extra context, if I put `import math` into the `globals.py` file by itself it gives the same error

**Comment by ovr** [comment]
Hello @SkinnyPigeon ,

It was Cube's issue. At that moment, we didn't support ARM64 (docker).

Could you give it a try with the latest release of Cube?

Thanks

**Comment by SkinnyPigeon** [comment]
Hi, that seems to be working now. I've got another issue but I'll open that separately. Thanks
